prepare_meta: add option keepmanifest; add color output
Change-Id: I7cab47b72306b56e747e90fb4e4be6ec569ee32f
Signed-off-by: Stephane Desneux <stephane.desneux@iot.bzh>

diff --git a/prepare_meta b/prepare_meta
--- a/prepare_meta
+++ b/prepare_meta
@@ -16,7 +16,7 @@
 
 # global variable containing the git repository where all manifests are stored
 
-VERSION=1.0.1
+VERSION=1.0.2
 
 MANIFEST_URL=https://github.com/iotbzh/agl-manifest.git
 
@@ -26,6 +26,7 @@ SCRIPT=$(basename $BASH_SOURCE)
 SELF_URL=https://raw.githubusercontent.com/iotbzh/agl-manifest/master/$SCRIPT
 
 set -e
+
 
 function usage() {
 	cat <<EOF >&2
@@ -60,6 +61,7 @@ Options:
          * wipeconfig: clear existing bitbake configuration if any (default: disabled)
          * keepcache: do not overwrite sstate-cache or download dir (default: disabled)
          * rm_work: do not keep working directory after each yocto package build. (Save LOT of space. default: disabled)
+         * keepmanifest: do not update agl-manifest (local git tree) by pulling from remote git repo: this allows local updates
    -d|--disable <option>
       disable a specific option
       available options: same as --enable
@@ -79,7 +81,36 @@ EOF
 	exit 1
 }
 
+stdout_in_terminal=0
+[[ -t 1 ]] && stdout_in_terminal=1
+function color {
+	[[ $stdout_in_terminal == 0 ]] && return
+	for k in $*; do
+		case $k in
+			bold) tput bold 2>/dev/null;;
+			none) tput sgr0 2>/dev/null;;
+			*) tput setaf $k 2>/dev/null;;
+		esac
+	done
+}
+color_green=$(color bold 2)
+color_yellow=$(color bold 3)
+color_red=$(color bold 1)
+color_none=$(color none)
+
+function error() {
+	echo "${color_red}$@${color_none}" >&2
+}
+
+function warning() {
+	echo "${color_yellow}$@${color_none}" >&2
+}
+
 function info() {
+	echo "${color_green}$@${color_none}" >&2
+}
+
+function log() {
 	echo "$@" >&2
 }
 
@@ -105,6 +136,7 @@ option_upgrade=1
 option_wipeconfig=0
 option_keepcache=0
 option_rm_work=0
+option_keepmanifest=0
 
 while true; do
 	case "$1" in
@@ -119,7 +151,7 @@ while true; do
 		-u|--upgrade) JUST_UPGRADE=1; shift ;;
 		-h|--help) HELP=1; shift ;;
 		--) shift; break;;
-		*) info "Internal error"; exit 1;;
+		*) error "Internal error"; exit 1;;
 	esac
 done
 
@@ -132,7 +164,7 @@ done
 [[ $# != 0 ]] && AGL_FEATURES="$@"
 
 # check git presence
-which git 2>&1 >/dev/null || { info "Unable to find git command."; exit 1; }
+which git 2>&1 >/dev/null || { error "Unable to find git command."; exit 1; }
 
 info "=============== SUMMARY =================="
 for v in \
@@ -145,7 +177,7 @@ for v in \
 	PROPRIETARY_RENESAS_DIR \
 	SELF_URL \
 	; do
-	info "$v : ${!v}"
+	log "$v : ${!v}"
 done
 info "=========================================="
 
@@ -156,9 +188,9 @@ function upgrade() {
 	local tempfile=$(mktemp /tmp/$SCRIPT.XXXXXXXX)
 	trap "rm -f $tempfile" STOP INT QUIT EXIT
 
-	echo -n  "Checking for upgrade ... "
+	log "Checking for upgrade ... "
 	# first, download reference script
-	wget --quiet -O $tempfile $SELF_URL || { info "Unable to check for upgrade. Remote script not accessible"; rm -f $tempfile; return 0; }
+	wget --quiet -O $tempfile $SELF_URL || { error "Unable to check for upgrade. Remote script not accessible"; rm -f $tempfile; return 0; }
 
 	local rc
 	{ diff -q $BASH_SOURCE $tempfile &>/dev/null; rc=$?; } || true # don't exit on error
@@ -176,7 +208,7 @@ function upgrade() {
 			info "a newer version of the script $SCRIPT is available."
 			;;
 		*)
-			info "Error while checking for upgrade on script $SCRIPT"
+			error "Error while checking for upgrade on script $SCRIPT"
 			rm $tempfile
 			$return_or_exit 0
 			;;
@@ -192,7 +224,7 @@ function upgrade() {
 
 	case $ans in
 		Y|y)
-			info "Upgrading script..."
+			log "Upgrading script..."
 			cp -v $BASH_SOURCE ${BASH_SOURCE}.old
 			cp -v $tempfile $BASH_SOURCE
 			chmod +x $BASH_SOURCE
@@ -205,7 +237,7 @@ function upgrade() {
 			;;
 	esac
 
-	info "Skipping upgrade."
+	warning "Skipping upgrade."
 	rm -f $tempfile
 }
 
@@ -218,20 +250,25 @@ function clone_or_pull() {
 	rev=${2:-}
 	dir=$(basename $url .git)
 
-	info "=== cloning $url / $rev into $PWD/$dir"
 	if [[ ! -d $dir ]]; then
+		info "=== cloning $url / $rev into $PWD/$dir"
 		git clone $url
 	fi
 
-	pushd $dir >/dev/null
-		for x in $(git remote); do
-			git fetch -p $x +refs/heads/*:refs/remotes/origin/* +refs/changes/*:refs/changes/*
-		done
-		[[ -z "$rev" ]] && rev=$(git rev-parse origin/HEAD)
-		git reset --hard
-		git clean -fd
-		git checkout -f $rev
-	popd >/dev/null
+	if [[ "$option_keepmanifest" == 0 ]]; then
+		info "=== updating $url (rev=$rev) into $PWD/$dir"
+		pushd $dir >/dev/null
+			for x in $(git remote); do
+				git fetch -p $x +refs/heads/*:refs/remotes/origin/* +refs/changes/*:refs/changes/*
+			done
+			[[ -z "$rev" ]] && rev=$(git rev-parse origin/HEAD)
+			git reset --hard
+			git clean -fd
+			git checkout -f $rev
+		popd >/dev/null
+	else
+		warning "Keeping $PWD/$dir unchanged"
+	fi
 }
 
 mkdir -p $DSTDIR/meta
@@ -257,15 +294,15 @@ pushd $DSTDIR/meta >/dev/null #{
 	clone_or_pull $MANIFEST_URL $rev
 
 	SRCDIR=$DSTDIR/meta/$(basename $MANIFEST_URL .git)/$flavour
-	[[ ! -d $SRCDIR ]] && { info "Unable to find flavour '$flavour'"; exit 1; }
+	[[ ! -d $SRCDIR ]] && { error "Unable to find flavour '$flavour'"; exit 1; }
 	info "=== SRCDIR: $SRCDIR"
 
 	# use latest manifest file
 	for x in $SRCDIR/*.manifest; do
-		[[ -n "$MANIFEST_FILE" ]] && info "Multiple manifest files found. Skipping $MANIFEST_FILE."
+		[[ -n "$MANIFEST_FILE" ]] && error "Multiple manifest files found. Skipping $MANIFEST_FILE."
 		MANIFEST_FILE=$x
 	done
-	[[ ! -f $MANIFEST_FILE ]] && { info "Unable to find manifest file for flavour $FLAVOUR"; exit 1; }
+	[[ ! -f $MANIFEST_FILE ]] && { error "Unable to find manifest file for flavour $FLAVOUR"; exit 1; }
 	info "=== MANIFEST_FILE: $MANIFEST_FILE"
 
 popd >/dev/null #}
@@ -289,7 +326,7 @@ function checkout_gits() {
 				REPO)
 					name="${value%%=*}"
 					url="${value#*=}"
-					info "Repository: $value"
+					log "Repository: $value"
 					if ! git remote | grep -q "^$name\$"; then
 						git remote add "$name" "$url"
 					elif ! git remote -v | awk '$1=="'$name'" && $2!="'$url'" {exit 1}'; then
@@ -297,7 +334,7 @@ function checkout_gits() {
 					fi
 					;;
 				HASH)
-					info "Using revision $value"
+					log "Using revision $value"
 					sha="${value%%=*}"
 					branch="${value#*=}"
 					for x in $(git remote); do
@@ -325,7 +362,7 @@ pushd $DSTDIR/meta >/dev/null #{
 		if [[ -f $file ]]; then
 			meta=$(basename $(dirname $file))
 
-			info "Patching meta $meta with patch $file"
+			log "Patching meta $meta with patch $file"
 
 			pushd $DSTDIR/meta/$meta >/dev/null
 				patch -p1 <$file
@@ -351,7 +388,7 @@ pushd $DSTDIR/meta >/dev/null #{
 	case "$TARGET" in
 		porter|m3ulcb|h3ulcb)
 			if [[ -d "$PROPRIETARY_RENESAS_DIR" ]]; then
-				echo "Using proprietary Renesas drivers for target $TARGET"
+				log "Using proprietary Renesas drivers for target $TARGET"
 				# cleanup spurious temp dir if any (may contain partially extracted files which lead to errors in rcar-genX setup scripts)
 				rm -rf $DSTDIR/meta/binary-tmp
 				# this will install the proprietary drivers at the right place and setup environment
@@ -367,7 +404,7 @@ pushd $DSTDIR/meta >/dev/null #{
 				rm -rf $DSTDIR/meta/binary-tmp
 				option_proprietary=1
 			else
-				echo "Initializing for $TARGET board without proprietary drivers"
+				log "Initializing for $TARGET board without proprietary drivers"
 				export TEMPLATECONF=$DSTDIR/meta/meta-renesas/meta-rcar-gen2/conf
 				source $DSTDIR/meta/poky/oe-init-build-env $DSTDIR/build >/dev/null
 			fi
