prepare_meta: introduce config files
Change-Id: I95ce1afd3aabe6fd44f7f977e47febac5445469d
Signed-off-by: Stephane Desneux <stephane.desneux@iot.bzh>

diff --git a/prepare_meta b/prepare_meta
--- a/prepare_meta
+++ b/prepare_meta
@@ -1,32 +1,73 @@
 #!/bin/bash
 
 ################################################################################
-
-# The MIT License (MIT)
+# 
+# Copyright (c) 2016-2019 Stéphane Desneux <sdx@iot.bzh>
 #
-# Copyright (c) 2016 Stéphane Desneux <sdx@iot.bzh>
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+# 
+#     http://www.apache.org/licenses/LICENSE-2.0
+# 
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
 #
-# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
-#
-# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-#
-# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
-
 ################################################################################
-
-# global variable containing the git repository where all manifests are stored
-
-VERSION=1.0.3
-
-MANIFEST_URL=https://github.com/iotbzh/agl-manifest.git
-
-SCRIPT=$(basename $BASH_SOURCE)
-
-# this script canonical url
-SELF_URL=https://raw.githubusercontent.com/iotbzh/agl-manifest/master/$SCRIPT
 
 set -e
 
+# external config can be loaded (if  any)
+SCRIPT=$(basename $BASH_SOURCE)
+
+CONFIG_FILES="$BASH_SOURCE.conf /etc/$SCRIPT.conf"
+if [[ -f /etc/xdtrc ]]; then
+	. /etc/xdtrc
+	CONFIG_FILES="$CONFIG_FILES $XDT_DIR/$SCRIPT.conf"
+fi
+CONFIG_FILES="$CONFIG_FILES ~/.config/$SCRIPT.conf"
+
+# --------- default values (can be overriden in config file)
+# global variable containing the git repository where all manifests are stored
+MANIFEST_URL=https://github.com/iotbzh/agl-manifest.git
+
+# this script canonical url
+SELF_URL=https://raw.githubusercontent.com/iotbzh/agl-manifest/master/$SCRIPT
+# or
+# accessible trough git protocol (ssh key typically):
+#SELF_URL=git@yourserver:project.git
+#SELF_URL_BRANCH=mybranch
+#SELF_URL_PATH=path/to/the/script/prepare_meta
+
+FLAVOUR=iotbzh
+AGL_FEATURES="agl-devel agl-netboot agl-appfw-smack agl-demo agl-localdev"
+DSTDIR=$(pwd -P)
+LOCALMIRROR=
+REMOTEMIRROR=
+PROPRIETARY_RENESAS_DIR=
+TARGET=m3ulcb
+JUST_UPGRADE=
+
+#default options values
+option_ccache=0
+option_upgrade=1
+option_wipeconfig=0
+option_keepcache=0
+option_rm_work=0
+option_keepmanifest=0
+option_cleartemp=0
+
+# --------- default values ------------------------------------
+
+echo "CONFIG FILES: $CONFIG_FILES" >&2
+for x in $CONFIG_FILES; do
+	[[ -f $x ]] && . $x
+done
+
+VERSION=1.0.4
 
 function usage() {
 	cat <<EOF >&2
@@ -117,28 +158,9 @@ function log() {
 
 # save global args in case we reuse them after upgrade
 GLOBAL_ARGS=("$@")
-
 TEMP=$(getopt -o f:o:l:r:p:e:d:t:uh --long flavour:,outputdir:,localmirror:,remotemirror:,proprietary:,enable:,disable:,target:,upgrade,help -n $SCRIPT -- "$@")
 [[ $? != 0 ]] && usage
 eval set -- "$TEMP"
-
-FLAVOUR=iotbzh
-AGL_FEATURES="agl-devel agl-netboot agl-appfw-smack agl-demo agl-localdev"
-DSTDIR=$(pwd -P)
-LOCALMIRROR=
-REMOTEMIRROR=
-PROPRIETARY_RENESAS_DIR=
-TARGET=porter
-JUST_UPGRADE=
-
-#default options values
-option_ccache=0
-option_upgrade=1
-option_wipeconfig=0
-option_keepcache=0
-option_rm_work=0
-option_keepmanifest=0
-option_cleartemp=0
 
 while true; do
 	case "$1" in
@@ -181,6 +203,8 @@ for v in \
 	REMOTEMIRROR \
 	PROPRIETARY_RENESAS_DIR \
 	SELF_URL \
+	SELF_URL_BRANCH \
+	SELF_URL_PATH \
 	; do
 	log "$v : ${!v}"
 done
@@ -195,7 +219,14 @@ function upgrade() {
 
 	log "Checking for upgrade ... "
 	# first, download reference script
-	wget --quiet -O $tempfile $SELF_URL || { error "Unable to check for upgrade. Remote script not accessible"; rm -f $tempfile; return 0; }
+	case $SELF_URL in
+		http://*|https://*)
+			wget --quiet -O $tempfile $SELF_URL || { error "Unable to check for upgrade. Remote script not accessible"; rm -f $tempfile; return 0; }
+			;;
+		*)
+			git archive --remote=$SELF_URL $SELF_URL_BRANCH $SELF_URL_PATH | tar xO $SELF_URL_PATH >$tempfile || { error "Unable to check for upgrade. Remote script not accessible"; rm -f $tempfile; return 0; }
+			;;
+	esac
 
 	local rc
 	{ diff -q $BASH_SOURCE $tempfile &>/dev/null; rc=$?; } || true # don't exit on error
