prepare_meta: generate run_aglsetup.sh to re-run aglsetup in same conditions
Change-Id: I3146dd1588fa2ee057f2b4f8f938164fafa42a92
Signed-off-by: Stephane Desneux <stephane.desneux@iot.bzh>

diff --git a/prepare_meta b/prepare_meta
--- a/prepare_meta
+++ b/prepare_meta
@@ -433,6 +433,46 @@ mkdir -p $DSTDIR/sstate-cache
 # wipe temp dir if requested
 [[ "$option_cleartemp" == "1" ]] && rm -rf $BUILDDIR/tmp
 
+function call_aglsetup() {
+	local script=$DSTDIR/meta/meta-agl/scripts/aglsetup.sh 
+	[[ ! -f $script ]] && { error "Unable to find $script"; return 1; }
+
+	# detect aglsetup version and add specific options if possible
+	local baseopts=""
+	# default version
+	local AGLSETUP_VERSION=1.0.0
+	# min version for --topic option
+	local topic_minver=1.2.0
+
+	source $script --version >/dev/null 2>&1 || true
+	if [[ "$(echo -e "$AGLSETUP_VERSION\n$topic_minver" | sort -V | head -n1)" == $topic_minver ]]; then
+		baseopts="$baseopts --topic 'flavour:$FLAVOUR'"
+	fi
+
+	# dump how aglsetup will be called
+	# IMPORTANT NOTE: -f is added, so that run_aglsetup.sh can be called directly (and overrides configuration!)
+	log "dumping aglsetup command line to $BUILDDIR/run_aglsetup.sh"
+	echo "#!/bin/bash" >$BUILDDIR/run_aglsetup.sh
+	if [[ -d "$PROPRIETARY_RENESAS_DIR" ]]; then
+		echo "export XDG_DOWNLOAD_DIR=$PROPRIETARY_RENESAS_DIR" >>$BUILDDIR/run_aglsetup.sh
+	fi
+	cat <<EOF >>$BUILDDIR/run_aglsetup.sh
+source $script -f $baseopts $@
+cat <<EOM
+
+---------------------------------------------------------
+WARNING from $0:
+     any extra config fragments generated by prepare_meta 
+     in $BUILDDIR/conf/*.inc 
+     are NOT added to local.conf
+---------------------------------------------------------
+EOM
+EOF
+	chmod +x $BUILDDIR/run_aglsetup.sh
+
+	source $script $baseopts "$@" >/dev/null
+}
+
 pushd $DSTDIR/meta >/dev/null #{
 	case "$TARGET" in
 		porter|m3ulcb|h3ulcb|salvator|m3ulcb-kingfisher)
@@ -444,7 +484,7 @@ pushd $DSTDIR/meta >/dev/null #{
 				# XDG_DOWNLOAD_DIR is used by meta-renesas/meta-rcar-gen2/scripts/setup_mm_packages.sh script to find zip files
 				export XDG_DOWNLOAD_DIR=$PROPRIETARY_RENESAS_DIR
 				if [[ -f $DSTDIR/meta/meta-agl/scripts/aglsetup.sh ]]; then
-					source $DSTDIR/meta/meta-agl/scripts/aglsetup.sh -m $TARGET -b $BUILDDIR $AGL_FEATURES >/dev/null
+					call_aglsetup -m $TARGET -b $BUILDDIR $AGL_FEATURES >/dev/null
 				else
 					# old setup script
 					source $DSTDIR/meta/meta-agl/scripts/envsetup.sh $TARGET $BUILDDIR >/dev/null
@@ -460,7 +500,7 @@ pushd $DSTDIR/meta >/dev/null #{
 			;;
 		*)
 			if [[ -f $DSTDIR/meta/meta-agl/scripts/aglsetup.sh ]]; then
-				source $DSTDIR/meta/meta-agl/scripts/aglsetup.sh -m $TARGET -b $BUILDDIR $AGL_FEATURES >/dev/null
+				call_aglsetup -m $TARGET -b $BUILDDIR $AGL_FEATURES >/dev/null
 			else
 				# old setup script
 				source $DSTDIR/meta/meta-agl/scripts/envsetup.sh $TARGET $BUILDDIR >/dev/null
