script/run_xnbd_server: enhance args parsing (image or machine)
Change-Id: Ib8726a7c1650164d4157e30afbd16602c0afac18
Signed-off-by: Stephane Desneux <stephane.desneux@iot.bzh>

diff --git a/scripts/bin/run_xnbd_server b/scripts/bin/run_xnbd_server
--- a/scripts/bin/run_xnbd_server
+++ b/scripts/bin/run_xnbd_server
@@ -3,20 +3,18 @@
 . /etc/xdtrc
 
 function usage() {
-	echo "$(basename $0) <machine>" >&2
+	echo "$(basename $0) <machine|ext4_filesystem>" >&2
 	echo "Machine is one of the following:" >&2
 	ls -d $XDT_BUILD/*/tmp/deploy/images/*  | xargs -n 1 basename >&2
 	exit 1
 }
 
-MACHINE=$1
-[[ -z "$MACHINE" ]] && { echo "Invalid machine" >&2; usage; }
+[[ -f "$1" ]] && IMAGE="$1" || MACHINE="${1:-*}"
+[[ -z "$IMAGE" ]] && { echo "Searching for image with MACHINE=$MACHINE..."; IMAGE=$(ls ${XDT_BUILD}/${MACHINE}/tmp/deploy/images/${MACHINE}/agl-*.ext4 | head -1); echo "Found ${IMAGE:-nothing}"; }
 
-IMAGE=${2:-$(ls ${XDT_BUILD}/${MACHINE}/tmp/deploy/images/${MACHINE}/agl-*.ext4 | head -1)}
+echo "Using IMAGE=$IMAGE"
 
-echo "Using MACHINE=$MACHINE IMAGE=$IMAGE"
-
-[[ ! -f $IMAGE ]] && { echo "Invalid image $IMAGE" >&2; usage; }
+[[ ! -f $IMAGE ]] && { echo "Invalid image or machine $1" >&2; usage; }
 
 REALIMG=$(realpath $IMAGE)
 [[ ! -f ${REALIMG}.bak ]] && cp -v ${REALIMG} ${REALIMG}.bak
