scripts/snapshot_gc: wip
Change-Id: Ifb0a947736b14a77de635824d2ff685dc65da39f
Signed-off-by: Stephane Desneux <stephane.desneux@iot.bzh>

diff --git a/scripts/bin/snapshot_gc b/scripts/bin/snapshot_gc
--- a/scripts/bin/snapshot_gc
+++ b/scripts/bin/snapshot_gc
@@ -20,6 +20,17 @@
 TOPDIR="${XDT_DIR}/deploy"
 PATTERN="^.*$"
 
+# retention policy:
+# keep last $DAYS
+# then keep last sunday for $WEEKS
+# then keep last sunday of each month for $MONTHS
+# then keep last sunday of last month of each $QUARTER
+# TOTAL: $DAYS + $(WEEKS+1) + $(MONTHS+1) + $(QUARTERS+1)
+DAYS=14
+WEEKS=2
+MONTHS=2
+QUARTERS=3
+
 usage() {
 	cat <<EOF >&2
 Usage: $(basename $BASH_SOURCE) [options]
@@ -62,38 +73,137 @@ done
 
 [[ "$HELP" == 1 ]] && usage
 
-info "Top dir: $TOPDIR"
-info "Pattern: $PATTERN"
+function compute_dates() {
+	function dt() {
+		date +%Y%m%d -d "$@"
+	}
 
-pushd $TOPDIR &>/dev/null || fatal "Invalid directory $TOPDIR" #{
+	local now=$(dt "${1:-now}")
+	
+	function previous_sunday() {
+		local cur=$1 dow
+		while true; do
+			dow=$(date +%u -d $cur)
+			[[ $dow == 7 ]] && break
+			cur=$(dt "$cur -1 day")
+		done
+		echo $cur
+	}
 
-	# list all objects matching pattern and beeing a folder
-	obj=$(find . -mindepth 1 -maxdepth 1 -type d)
-	echo $obj 
+	function last_sunday_previous_month() {
+		local cur=$1
+		cur=$(date +%Y%m01 -d $cur)
+		cur=$(dt "$cur -1 day")
+		cur=$(previous_sunday $cur)
+		echo $cur
+	}
 
-popd &>/dev/null #}
+	function last_sunday_previous_quarter() {
+		local cur=$1 month qmonth
+		month=$(date +%m -d $cur)
+		month=${month#0}
+		qmonth=$(printf "%02d" $(( month-(month-1)%3 )) ) # first month of the quarter
+		cur=$(date +%Y${qmonth}01 -d $cur) # first day of the quarter
+		cur=$(dt "$cur -1 day")
+		cur=$(previous_sunday $cur)
+		echo $cur
+	}
 
-function dt() {
-	res=$(date +%Y%m%d -d "$@")
-	#log "$@": $res 
-	echo $res
+	# build the list of accepted dates
+	local dates
+
+	# last n days
+	dates=$now
+	for x in $(seq 2 $DAYS); do 
+		now=$(dt "$now -1 day")
+		dates="$dates $now"
+	done
+
+	# find preceding sunday and take n weeks
+	now=$(dt "$now -1 day")
+	now=$(previous_sunday $now)
+	dates="$dates $now"
+	for x in $(seq 1 $WEEKS); do 
+		now=$(dt "$now -1 week")
+		dates="$dates $now"
+	done
+
+	# find last sunday of each month in previous months
+	now=$(last_sunday_previous_month $now)
+	dates="$dates $now"
+	for x in $(seq 1 $MONTHS); do 
+		now=$(last_sunday_previous_month $now)
+		dates="$dates $now"
+	done
+
+	# find last sunday of each quarter in previous quarters
+	now=$(last_sunday_previous_quarter $now)
+	dates="$dates $now"
+	for x in $(seq 1 $QUARTERS); do 
+		now=$(last_sunday_previous_quarter $now)
+		dates="$dates $now"
+	done
+
+	echo $dates
 }
 
-# build the list of accepted dates, beyond last week
-start=$(dt "now")
+function debug_dates() {
+	for x in $(compute_dates "$@"); do
+		echo $x $(date "+%a" -d $x)
+	done
+}
 
-dates=$start
-dates="$dates /"
+function find_snapshots() {
+	local dir=$1
+	local pattern=$2
+#	info "Finding snapshots in $dir matching $pattern"
 
-for x in $(seq 1 14); do dates="$dates $(dt "$start -$x days")"; done
-dates="$dates /"
+	pushd $dir &>/dev/null || fatal "Invalid directory $dir" #{
+		# list all objects matching pattern and beeing a folder
+		for x in $(find . -mindepth 1 -maxdepth 1 -type d -printf "%f\n"); do
+			[[ "$x" =~ $pattern ]] && echo $x
+		done
+	popd &>/dev/null #}
+}
 
-for x in $(seq 1 6); do dates="$dates $(dt "$start -$x weeks")"; done
+function simulate() {
+	local tmpdir=/tmp/simulate_gc
+	local prefix=Snapshot_
+	rm -rf $tmpdir
+	mkdir -p $tmpdir
+	for day in {0..600}; do
+		now=$(date +%Y%m%d -d "20170101 +$day days")
+		mkdir $tmpdir/${prefix}$now
+		keepdates=$(compute_dates $now)
+		snapshots=$(find_snapshots $tmpdir "^$prefix.*$")
+		echo -n $now: $(wc -w <<<$snapshots) snapshots.
+		for x in $(find_snapshots $tmpdir "^${prefix}_.*$"); do
+			sdt=${x#$prefix}
+			grep -q $sdt <<<$keepdates || {
+				echo -n " -$x"
+				rmdir $tmpdir/$x
+			}
+		done
+		echo
+	done
+}
 
+function get_snapshots_age() {
+	local tmpdir=/tmp/simulate_gc
+	local prefix=Snapshot_
+	local snapshots=$(find_snapshots $tmpdir "^$prefix.*$")
 
-# debug
-for x in $dates; do
-	[[ $x == "/" ]] && { echo "---"; continue; }
-	echo $x:$(date "+%Y%m%d %a" -d $x)
-done
-echo $dates
+	local tsnow=$(date +%s -d "${1:-now}")
+	local sdt age days hours
+	for x in $snapshots; do
+		sdt=${x#$prefix}
+		age=$(( ($tsnow - $(date +%s -d $sdt))/3600 ))
+		hours=$(( age % 24 ))
+		days=$(( age / 24 )) # in days
+		printf "%s %03dd.%02dh\n" $x $days $hours
+	done
+}
+
+#debug_dates "$@"
+#simulate
+get_snapshots_age "$@"
