snaptool: wip
Change-Id: Ia65a54b7f37ffe61c242c38172613a850a151ec3
Signed-off-by: Stephane Desneux <stephane.desneux@iot.bzh>

diff --git a/scripts/bin/snaptool b/scripts/bin/snaptool
--- a/scripts/bin/snaptool
+++ b/scripts/bin/snaptool
@@ -16,332 +16,75 @@
 
 set -e
 
-# load libzh
-. $(dirname $BASH_SOURCE)/libzh.sh
+MYNAME=$(basename $BASH_SOURCE .sh)
 
-# specify config file
-CONFIG_FILE=${SNAPTOOL_CONF:-$XDT_DIR/snaptool.conf}
+# load libsnaptool
+. $(dirname $BASH_SOURCE)/libsnaptool.sh
 
 # ------------------------- options parsing -------------------------------------
+
+function __getbuiltincommands() {
+	# enumerate all:
+	# - functions named command_xxxx
+	# - scripts named snaptool-xxxx
+	local builtins=$(typeset -F | awk '{print $3;}' | grep ^command_ | sort)
+
+	echo $builtins
+}
+function __getfilecommands() {
+	local external=$(find $(dirname $BASH_SOURCE) -name "${MYNAME}-*" | xargs basename | sort)
+	echo $external
+}
+
+function __callcommand() {
+	cmd=$1
+	shift
+	local funcname=command_$cmd
+	if [[ $(type -t $funcname) == "function" ]]; then
+		COMMAND=$(basename $BASH_SOURCE .sh)-$cmd
+		$funcname "$@"
+		return $?
+	fi
+
+	# find file
+	local extname=$(dirname $BASH_SOURCE)/${MYNAME}-$cmd
+	if [[ -f $extname ]]; then
+		$extname "$@"
+		return $?
+	fi
+
+	error "Command $cmd not found"
+	return 1
+}
 
 function __global_usage() {
 	cat <<EOF >&2
 General usage: $(basename $BASH_SOURCE) <command> [options]
 
-To get command specific help:
-	$(basename $BASH_SOURCE) help <command>
-
 Available commands:
 EOF
 	# help for other commands
-	local commands=$(typeset -F | awk '{print $3;}' | grep ^command_ | sort)
-	for x in $commands; do 
-		echo -e "\t${x#command_}" >&2
+	for x in $(__getbuiltincommands); do
+		echo "   ${x#command_} (builtin)" >&2
+	done
+	for x in $(__getfilecommands); do
+		echo "   ${x#$MYNAME-} (external)" >&2
 	done
 	echo >&2
-	for x in $commands; do 
- 		local func=usage_${x#command_}
-		[[ $(type -t $func) == "function" ]] && {
-			COMMAND="$(basename $BASH_SOURCE) ${x#command_}"
-			$func >&2
-			echo >&2
-		}
-	done
+
 	exit 0
 }
 
-declare -A MIRROR RESOURCES BUILD DEPLOY
+# parse command and run it
+[[ $# == 0 ]] && { __global_usage; exit 1; }
 
-function __configure() {
-	# create config file if needed
-	[[ ! -f $CONFIG_FILE ]] && {
-		info "Creating config file $CONFIG_FILE"
-		touch $CONFIG_FILE || fatal "Unable to create config file $CONFIG_FILE"
-		cat <<EOF >$CONFIG_FILE
-# configuration file for snaptool
-# see https://github.com/iotbzh/agl-manifest/tree/master/scripts for more information
-
-# how mirror can be mounted/unmounted and accessed locally
-MIRROR[path]=$HOME/mirror
-MIRROR[mount]=
-MIRROR[umount]=
-
-RESOURCES[path]=$HOME/mirror/proprietary-renesas-r-car
-RESOURCES[mount]=
-RESOURCES[umount]=
-
-# temp build folder
-BUILD[path]=$XDT_DIR
-BUILD[mount]=
-BUILD[umount]=
-
-# deployment folder
-DEPLOY[path]=$XDT_DIR/deploy
-DEPLOY[mount]=
-DEPLOY[umount]=
-EOF
-	}
-	[[ ! -f $CONFIG_FILE ]] && fatal "Unable to find config file $CONFIG_FILE"
-
-	# load configuration file
-	info "Loading config file $CONFIG_FILE"
-	. $CONFIG_FILE
+#special case for help command
+cmd=$1
+shift
+[[ "$cmd" =~ ^(-h|--help|help)$ ]] && {
+	__global_usage
+	exit 1
 }
 
-function __main() {
-	setdebug 1
+__callcommand $cmd "$@"
 
-	__configure
-
-	# special case for help
-	[[ "$1" =~ ^(-h|--help|help)$ ]] && {
-		shift
-		COMMAND="$(basename $BASH_SOURCE) $1"
-		USAGE="usage_$1"
-		[[ -n "$1" ]] && $USAGE || __global_usage
-		exit 0
-	}
-
-	COMMAND=$1
-	shift || { __global_usage; exit 1; }
-
-	# function "command_$COMMAND" must exist
-	USAGE="usage_$COMMAND"
-	funcname="command_$COMMAND"
-	[[ "$(type -t $funcname)" != "function" ]] && { error "Unknown command $COMMAND"; __global_usage; exit 1; }
-	COMMAND="$(basename $BASH_SOURCE) $COMMAND"
-	$funcname "$@" 
-}
-
-# ------------------------ ops on folder -----------------------------------------
-
-FOLDERS="MIRROR RESOURCES BUILD DEPLOY"
-
-function folders_check() {
-	for x in $FOLDERS; do
-		typeset -n folder=$x
-		[[ ! -d ${folderx[path]} ]] && { error "Directory '${folder[path]}' ($x) doesn't exist"; return 1; }
-		debug "Directory ${x[path]} is available"
-	done
-	return 0
-}
-
-function folders_mount() {
-	for x in $FOLDERS; do
-		typeset -n folder=$x
-		[[ -n "${folder[mount]}" ]] && echo "Running mount command for $x: ${folder[mount]}"
-	done
-}
-
-function folders_umount() {
-	for x in $FOLDERS; do
-		typeset -n folder=$x
-		[[ -n "${folder[umount]}" ]] && echo "Running umount command for $x: ${folder[umount]}"
-	done
-}
-
-# --------------------------- retention policy in deploy dir -------------------
-
-# compute dates to keep
-function compute_retention_dates() {
-	function dt() {
-		date --utc +%Y%m%d -d "$@"
-	}
-
-	local now=$(dt "${1:-now}")
-	
-	function previous_sunday() {
-		local cur=$1 dow
-		while true; do
-			dow=$(date --utc +%u -d $cur)
-			[[ $dow == 7 ]] && break
-			cur=$(dt "$cur -1 day")
-		done
-		echo $cur
-	}
-
-	function last_sunday_previous_month() {
-		local cur=$1
-		cur=$(date --utc +%Y%m01 -d $cur)
-		cur=$(dt "$cur -1 day")
-		cur=$(previous_sunday $cur)
-		echo $cur
-	}
-
-	function last_sunday_previous_quarter() {
-		local cur=$1 month qmonth
-		month=$(date --utc +%m -d $cur)
-		month=${month#0}
-		qmonth=$(printf "%02d" $(( month-(month-1)%3 )) ) # first month of the quarter
-		cur=$(date --utc +%Y${qmonth}01 -d $cur) # first day of the quarter
-		cur=$(dt "$cur -1 day")
-		cur=$(previous_sunday $cur)
-		echo $cur
-	}
-
-	# build the list of accepted dates
-	local dates
-
-	# last n days
-	dates=$now
-	for x in $(seq 2 $DAYS); do 
-		now=$(dt "$now -1 day")
-		dates="$dates $now"
-	done
-
-	# find preceding sunday and take n weeks
-	now=$(dt "$now -1 day")
-	now=$(previous_sunday $now)
-	dates="$dates $now"
-	for x in $(seq 1 $WEEKS); do 
-		now=$(dt "$now -1 week")
-		dates="$dates $now"
-	done
-
-	# find last sunday of each month in previous months
-	now=$(last_sunday_previous_month $now)
-	dates="$dates $now"
-	for x in $(seq 1 $MONTHS); do 
-		now=$(last_sunday_previous_month $now)
-		dates="$dates $now"
-	done
-
-	# find last sunday of each quarter in previous quarters
-	now=$(last_sunday_previous_quarter $now)
-	dates="$dates $now"
-	for x in $(seq 1 $QUARTERS); do 
-		now=$(last_sunday_previous_quarter $now)
-		dates="$dates $now"
-	done
-
-	echo $dates
-}
-
-function find_snapshots() {
-	local dir=$1
-	local pattern=$2
-	debug "Finding snapshots in $dir matching $pattern"
-
-	pushd $dir &>/dev/null || fatal "Invalid directory $dir" #{
-		# list all objects matching pattern and beeing a folder
-		for x in $(find . -mindepth 1 -maxdepth 1 -type d -printf "%f\n"); do
-			[[ "$x" =~ $pattern ]] && echo $x
-		done
-	popd &>/dev/null #}
-}
-
-function simulate_gc() {
-	local tmpdir=/tmp/simulate_gc
-	local prefix=Snapshot_
-	rm -rf $tmpdir
-	mkdir -p $tmpdir
-	for day in {0..600}; do
-		now=$(date --utc +%Y%m%d -d "20170101 +$day days")
-		mkdir $tmpdir/${prefix}$now
-		keepdates=$(compute_retention_dates $now)
-		snapshots=$(find_snapshots $tmpdir "^$prefix.*$")
-		echo -n $now: $(wc -w <<<$snapshots) snapshots.
-		for x in $(find_snapshots $tmpdir "^${prefix}_.*$"); do
-			sdt=${x#$prefix}
-			grep -q $sdt <<<$keepdates || {
-				echo -n " -$x"
-				rmdir $tmpdir/$x
-			}
-		done
-		echo
-	done
-}
-
-function get_snapshots_age() {
-	local tmpdir=/tmp/simulate_gc
-	local prefix=Snapshot_
-	local snapshots=$(find_snapshots $tmpdir "^$prefix.*$")
-
-	local tsnow=$(date --utc +%s -d "${1:-now}")
-	local sdt age days hours
-	for x in $snapshots; do
-		sdt=${x#$prefix}
-		age=$(( ($tsnow - $(date --utc +%s -d $sdt))/3600 ))
-		hours=$(( age % 24 ))
-		days=$(( age / 24 )) # in days
-		printf "%s %03dd.%02dh\n" $x $days $hours
-	done
-}
-
-# ------------------------- top level commands ----------------------------------
-
-function usage_prepare() {
-	cat <<EOF >&2
-Usage: $COMMAND [options] 
-	options:
-		-n|--dryrun : do nothing
-EOF
-}
-function command_prepare() {
-	local opts="-o n --long dryrun" tmp
-	tmp=$(getopt $opts -n "$COMMAND" -- "$@" 2>/dev/null) || {
-		tmp=$(getopt $opts -n "$COMMAND" -- "$@" 2>&1 >/dev/null) || true
-		error $tmp; $USAGE; return 1
-	}
-	eval set -- $tmp
-
-	local dryrun=
-
-	while true; do	
-		case "$1" in 
-			-n|--dryrun) dryrun=1; shift;;
-			--) shift; break;;
-			*) fatal "Internal error";;
-		esac
-	done
-
-	# ----------
-
-	folders_check
-}
-
-function usage_mount() {
-	cat <<EOF >&2
-Usage: $COMMAND [options] 
-	options:
-		-n|--dryrun : do nothing
-EOF
-}
-function command_mount() {
-	local opts="-o n --long dryrun" tmp
-	tmp=$(getopt $opts -n "$COMMAND" -- "$@" 2>/dev/null) || {
-		tmp=$(getopt $opts -n "$COMMAND" -- "$@" 2>&1 >/dev/null) || true
-		error $tmp; $USAGE; return 1
-	}
-	eval set -- $tmp
-
-	local dryrun=
-
-	while true; do	
-		case "$1" in 
-			-n|--dryrun) dryrun=1; shift;;
-			--) shift; break;;
-			*) fatal "Internal error";;
-		esac
-	done
-
-	# ----------
-	
-	debug "dryrun=$dryrun args=$@"
-}
-
-function command_umount() {
-	true
-}
-function command_gcdebug() {
-	debug "Retention dates:"
-	for x in $(compute_dates "$@"); do
-		debug $x $(date --utc "+%a" -d $x)
-	done
-	#simulate
-	#get_snapshots_age "$@"
-}
-
-# ----------------------------------------------------------------------
-
-__main "$@"
