scripts: add build time in reports
Change-Id: I71f3630e66fd61ae8a11a446b1952d3bbda24dcd
Signed-off-by: Stephane Desneux <stephane.desneux@iot.bzh>

diff --git a/scripts/build_all_boards b/scripts/build_all_boards
--- a/scripts/build_all_boards
+++ b/scripts/build_all_boards
@@ -24,11 +24,15 @@ function run_prepare_meta() {
 }
 
 function runbitbake() {
+	local ts0=$(date +%s)
 	echo bitbake "$@" >>$CMDLOG
 	bitbake "$@" 
-	rc=$?
+	local rc=$?
+	local ts1=$(date +%s)
+	local dt=$(( $ts1 - $ts0 ))
+	local dtstr=$(date +%H:%M:%S -u --date="@$dt")
 	eval $(bitbake -e | grep ^MACHINE_ARCH)
-	echo ${MACHINE_ARCH:-unknown} $BUILD_FLAVOUR $([[ $rc == 0 ]] && echo "OK" || echo "FAIL($rc)") >>$RESLOG
+	echo ${MACHINE_ARCH:-unknown} $BUILD_FLAVOUR $dtstr $([[ $rc == 0 ]] && echo "OK" || echo "FAIL($rc)") >>$RESLOG
 	return $rc
 }
 
